##Sample Dataset

In [4]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta


n_samples = 1000
missing_rate = 0.05 


data_config = {
    "id": range(1, n_samples + 1),
    "uprn": lambda: f"1000{np.random.randint(10000000, 99999999)}",
    "address": [f"{np.random.randint(1, 200)} {street}" for street in 
                ["Main Street", "High Street", "Park Road", "Church Lane", "Station Road"] * 200],
    "city": ["Glasgow", "Edinburgh", "Aberdeen", "Dundee", "Inverness", "London", "Manchester", "Birmingham", "Cardiff", "Belfast", None],
    "region": ["Scotland", "England", "Wales", "Northern Ireland", None],
    "postcode": lambda: f"{np.random.choice(['G', 'EH', 'AB', 'DD'])}{np.random.randint(1, 99)} {np.random.randint(1, 9)}{np.random.choice(['AB', 'CD', 'EF', 'GH'])}",
    "lat": (50.0, 59.0),  
    "lon": (-8.0, 2.0),   
    "buildYear": (1950, 2025),
    "type": ["High-Rise Flat", "Detached House", "Semi-Detached", "Terraced", "Bungalow", "Apartment", None],
    "tenure": ["Social Rent", "Owner Occupied", "Private Rent", "Shared Ownership", None],
    "landlord": ["Clyde Housing", "City Council", "Private Landlord", "Housing Association", None],
    "epcRating": ["A", "B", "C", "D", "E", "F", "G", None],
    "deprivationIndex": (1.0, 10.0),
    "floodScore": (0.0, 1.0),
    "crimeIndex": (1.0, 10.0),
    "lastClaimDate": lambda: (datetime.now() - timedelta(days=np.random.randint(0, 1825))).strftime("%Y-%m-%d"),
    "claimFrequency": (0.0, 2.0),
    "expectedSeverity": (500, 10000),
    "purePremium": (100, 2000),
    "maintenanceScore": (1.0, 10.0),
    "voidDaysLastYear": (0, 365),
    "riskBand": ["Very Low", "Low", "Medium", "High", "Very High", None]
}

In [5]:
def generate_column(config, size):
    if callable(config):
        return [config() for _ in range(size)]
    elif isinstance(config, list):
        return np.random.choice(config, size)
    elif isinstance(config, tuple) and len(config) == 2:
        if isinstance(config[0], float):
            return np.round(np.random.uniform(config[0], config[1], size), 2)
        else:
            return np.random.randint(config[0], config[1], size)
    elif isinstance(config, range):
        return list(config)
    return config

In [6]:
df = pd.DataFrame()
for col, config in data_config.items():
    df[col] = generate_column(config, n_samples)

In [7]:
df.head()

,id,uprn,address,city,region,postcode,lat,lon,buildYear,type,...,deprivationIndex,floodScore,crimeIndex,lastClaimDate,claimFrequency,expectedSeverity,purePremium,maintenanceScore,voidDaysLastYear,riskBand
0,1,100084475106,18 Park Road,Manchester,Wales,AB40 2GH,55.21,-3.71,2014,None,...,4.38,0.56,7.33,2022-09-18,1.44,2123,736,4.21,290,Very Low
1,2,100045329879,160 Main Street,Belfast,England,AB57 5AB,55.43,-2.15,2014,None,...,5.71,0.11,4.32,2023-04-23,1.35,5091,523,8.51,99,Very High
2,3,100079434601,52 Church Lane,Dundee,England,G91 5GH,58.36,1.30,2002,None,...,5.31,0.04,7.49,2025-09-05,0.85,3609,1432,2.65,284,Very Low
3,4,100017737414,149 Park Road,Glasgow,Northern Ireland,DD22 6EF,55.43,1.31,1968,Detached House,...,8.83,0.20,5.22,2025-06-09,0.12,1356,345,6.55,319,None
4,5,100097137528,91 High Street,Birmingham,None,EH82 2GH,52.00,-6.30,1999,Terraced,...,7.67,0.95,6.69,2022-07-25,1.57,554,927,6.50,208,Very High

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                1000 non-null   int64
 1   uprn              1000 non-null   object
 2   address           1000 non-null   object
 3   city              914 non-null    object
 4   region            790 non-null    object
 5   postcode          1000 non-null   object
 6   lat               1000 non-null   float64
 7   lon               1000 non-null   float64
 8   buildYear         1000 non-null   int32
 9   type              855 non-null    object
 10  tenure            822 non-null    object
 11  landlord          798 non-null    object
 12  epcRating         871 non-null    object
 13  deprivationIndex  1000 non-null   float64
 14  floodScore        1000 non-null   float64
 15  crimeIndex        1000 non-null   float64
 16  lastClaimDate     1000 non-null   object
 17  claimFrequency    1000 non-null   float64
 18  expectedSeverity  1000 non-null   int32
 19  purePremium       1000 non-null   int32
 20  maintenanceScore  1000 non-null   float64
 21  voidDaysLastYear  1000 non-null   int32
 22  riskBand          833 non-null    object
dtypes: float64(7), int32(4), int64(1), object(11)
memory usage: 164.2+ KB

In [9]:
import re

def normalize_column_name(col_name):
    """Normalize column names to snake_case."""
    # Strip leading/trailing whitespace
    col_name = col_name.strip()
    # Lowercase the column name
    col_name = col_name.lower()
    # Spaces and hyphens to underscores
    col_name = re.sub(r'[\s\-]+', '_', col_name)
    # Remove special characters
    col_name = re.sub(r'[^\w_]', '', col_name)
    return col_name

In [10]:
df.columns = [normalize_column_name(col) for col in df.columns]

In [11]:
df.head()

,id,uprn,address,city,region,postcode,lat,lon,buildyear,type,...,deprivationindex,floodscore,crimeindex,lastclaimdate,claimfrequency,expectedseverity,purepremium,maintenancescore,voiddayslastyear,riskband
0,1,100084475106,18 Park Road,Manchester,Wales,AB40 2GH,55.21,-3.71,2014,None,...,4.38,0.56,7.33,2022-09-18,1.44,2123,736,4.21,290,Very Low
1,2,100045329879,160 Main Street,Belfast,England,AB57 5AB,55.43,-2.15,2014,None,...,5.71,0.11,4.32,2023-04-23,1.35,5091,523,8.51,99,Very High
2,3,100079434601,52 Church Lane,Dundee,England,G91 5GH,58.36,1.30,2002,None,...,5.31,0.04,7.49,2025-09-05,0.85,3609,1432,2.65,284,Very Low
3,4,100017737414,149 Park Road,Glasgow,Northern Ireland,DD22 6EF,55.43,1.31,1968,Detached House,...,8.83,0.20,5.22,2025-06-09,0.12,1356,345,6.55,319,None
4,5,100097137528,91 High Street,Birmingham,None,EH82 2GH,52.00,-6.30,1999,Terraced,...,7.67,0.95,6.69,2022-07-25,1.57,554,927,6.50,208,Very High

In [12]:
COLUMN_MAPPING = {
    'id': ['id', 'property_id', 'prop_id', 'reference', 'ref_number'],
    'uprn': ['uprn', 'unique_property_reference', 'property_reference'],
    'address': ['address', 'full_address', 'property_address', 'street_address'],
    'city': ['city', 'town', 'locality'],
    'postcode': ['postcode', 'post_code', 'zip_code', 'postal_code'],
    'buildYear': ['buildyear', 'build_year', 'year_built', 'construction_year', 'built'],
    'type': ['type', 'property_type', 'dwelling_type', 'house_type'],
    'tenure': ['tenure', 'ownership', 'tenancy_type'],
    'landlord': ['landlord', 'owner', 'landlord_name', 'housing_provider'],
    'epcRating': ['epcrating', 'epc_rating', 'epc', 'energy_rating', 'energy_performance'],
    'lastClaimDate': ['lastclaimdate', 'last_claim_date', 'lastclaim', 'previous_claim', 
                      'last_claim', 'claim_date', 'most_recent_claim'],
    'claimFrequency': ['claimfrequency', 'claim_frequency', 'number_of_claims', 'claims_count'],
    'riskBand': ['riskband', 'risk_band', 'risk_level', 'risk_category', 'risk_rating']
}

def standardize_columns(df, mapping=COLUMN_MAPPING):
    normalized_cols = {col: normalize_column_name(col) for col in df.columns}
    
    # Create reverse mapping from variants to standard names
    reverse_mapping = {}
    for standard_name, variants in mapping.items():
        for variant in variants:
            reverse_mapping[normalize_column_name(variant)] = standard_name
    
    # Create rename dictionary
    rename_dict = {}
    for original_col, normalized_col in normalized_cols.items():
        if normalized_col in reverse_mapping:
            rename_dict[original_col] = reverse_mapping[normalized_col]
    
    df_standardized = df.rename(columns=rename_dict)
    
    # Print the renamed columns
    if rename_dict:
        print("Renamed columns:")
        for old, new in rename_dict.items():
            print(f"  '{old}' → '{new}'")
    
    return df_standardized

In [13]:
df = standardize_columns(df)

Renamed columns:
  'id' → 'id'
  'uprn' → 'uprn'
  'address' → 'address'
  'city' → 'city'
  'postcode' → 'postcode'
  'buildyear' → 'buildYear'
  'type' → 'type'
  'tenure' → 'tenure'
  'landlord' → 'landlord'
  'epcrating' → 'epcRating'
  'lastclaimdate' → 'lastClaimDate'
  'claimfrequency' → 'claimFrequency'
  'riskband' → 'riskBand'

In [14]:
import pandas as pd
import numpy as np
import re
from datetime import datetime

In [15]:
def detect_postcode_column(series, threshold=0.7):
    """
    Detect if column contains UK postcodes.
    Returns confidence score (0-1).
    """
    uk_postcode_pattern = re.compile(
        r'^[A-Z]{1,2}\d{1,2}[A-Z]?\s*\d[A-Z]{2}$',
        re.IGNORECASE
    )
    
    non_null = series.dropna().astype(str).str.strip()
    if len(non_null) == 0:
        return 0.0
    
    matches = non_null.str.match(uk_postcode_pattern).sum()
    confidence = matches / len(non_null)
    
    return confidence if confidence >= threshold else 0.0

In [16]:
def detect_uprn_column(series, threshold=0.7):
    """
    Detect if column contains UPRN (Unique Property Reference Number).
    UPRNs are typically 12-digit numbers.
    Returns confidence score (0-1).
    """
    non_null = series.dropna().astype(str).str.strip()
    if len(non_null) == 0:
        return 0.0
    
    # Remove non-digits and check length
    digits_only = non_null.str.replace(r'\D', '', regex=True)
    matches = (digits_only.str.len() == 12).sum()
    confidence = matches / len(non_null)
    
    return confidence if confidence >= threshold else 0.0

In [17]:
def detect_date_column(series, threshold=0.7):
    """
    Detect if column contains dates.
    Returns confidence score (0-1) and inferred format if detected.
    """
    non_null = series.dropna().astype(str)
    if len(non_null) == 0:
        return 0.0, None
    
    formats = [
        '%Y-%m-%d',      # 2023-01-15
        '%d/%m/%Y',      # 15/01/2023
        '%m/%d/%Y',      # 01/15/2023 
        '%d-%m-%Y',      # 15-01-2023
        '%Y/%m/%d',      # 2023/01/15
        '%d.%m.%Y',      # 15.01.2023
        '%Y%m%d',        # 20230115
    ]
    best_confidence = 0.0
    best_format = None
    
    for fmt in formats:
        try:
            parsed = pd.to_datetime(non_null, format=fmt, errors='coerce')
            valid = parsed.notna().sum()
            confidence = valid / len(non_null)
            
            if confidence > best_confidence:
                best_confidence = confidence
                best_format = fmt
        except:
            continue
    
    return (best_confidence if best_confidence >= threshold else 0.0), best_format

In [18]:
def detect_address_column(series, threshold=0.6):
    """
    Detect if column contains street addresses.
    Looks for common UK street indicators.
    Returns confidence score (0-1).
    """
    street_indicators = [
        r'\bstreet\b', r'\bst\b', r'\broad\b', r'\brd\b',
        r'\blive\b', r'\bave\b', r'\bavenue\b', r'\bclose\b',
        r'\bcourt\b', r'\bterrace\b', r'\bplace\b', r'\bsquare\b',
        r'\bway\b', r'\bcrescent\b', r'\bdrive\b', r'\bgardens\b'
    ]
    
    non_null = series.dropna().astype(str).str.lower()
    if len(non_null) == 0:
        return 0.0
    
    # Check for street indicators + numbers
    pattern = '|'.join(street_indicators)
    has_indicator = non_null.str.contains(pattern, regex=True, na=False)
    has_number = non_null.str.contains(r'\d', regex=True, na=False)
    
    matches = (has_indicator & has_number).sum()
    confidence = matches / len(non_null)
    
    return confidence if confidence >= threshold else 0.0

In [19]:
def detect_numeric_id_column(series, threshold=0.9):
    """
    Detect if column is a numeric ID (sequential or random integers).
    Returns confidence score (0-1) and whether it's sequential.
    """
    non_null = series.dropna()
    if len(non_null) == 0:
        return 0.0, False
    
    # Check if numeric
    numeric = pd.to_numeric(non_null, errors='coerce')
    numeric_ratio = numeric.notna().sum() / len(non_null)
    
    if numeric_ratio < threshold:
        return 0.0, False
    
    # Check if sequential
    numeric_clean = numeric.dropna().astype(int)
    if len(numeric_clean) > 1:
        diffs = numeric_clean.diff().dropna()
        is_sequential = (diffs == 1).mean() > 0.9
    else:
        is_sequential = False
    
    return numeric_ratio, is_sequential

In [20]:
def detect_categorical_column(series, max_unique_ratio=0.05):
    """
    Detect if column is categorical (low cardinality).
    Returns confidence score and unique count.
    """
    non_null_count = series.notna().sum()
    if non_null_count == 0:
        return 0.0, 0
    
    unique_count = series.nunique(dropna=True)
    unique_ratio = unique_count / non_null_count
    
    # High confidence if very few unique values
    if unique_ratio <= max_unique_ratio:
        confidence = 1.0 - unique_ratio
    else:
        confidence = 0.0
    
    return confidence, unique_count

In [21]:
def detect_boolean_column(series, threshold=0.8):
    """
    Detect if column contains boolean-like values.
    Returns confidence score (0-1).
    """
    non_null = series.dropna().astype(str).str.strip().str.lower()
    if len(non_null) == 0:
        return 0.0
    
    boolean_values = {
        'yes', 'no', 'true', 'false', '1', '0',
        'y', 'n', 't', 'f'
    }
    
    matches = non_null.isin(boolean_values).sum()
    confidence = matches / len(non_null)
    
    return confidence if confidence >= threshold else 0.0

In [22]:
def detect_year_column(series, threshold=0.8):
    """
    Detect if column contains year values (1900-2100).
    Returns confidence score (0-1).
    """
    non_null = pd.to_numeric(series, errors='coerce').dropna()
    if len(non_null) == 0:
        return 0.0
    
    in_year_range = ((non_null >= 1900) & (non_null <= 2100)).sum()
    confidence = in_year_range / len(non_null)
    
    return confidence if confidence >= threshold else 0.0

In [23]:
def detect_coordinate_column(series, lat_or_lon='lat', threshold=0.8):
    """
    Detect if column contains geographic coordinates.
    lat_or_lon: 'lat' for latitude or 'lon' for longitude
    Returns confidence score (0-1).
    """
    non_null = pd.to_numeric(series, errors='coerce').dropna()
    if len(non_null) == 0:
        return 0.0
    
    if lat_or_lon == 'lat':
        # UK latitude range: approximately 49-61
        in_range = ((non_null >= 49.0) & (non_null <= 61.0)).sum()
    else:  # lon
        # UK longitude range: approximately -8 to 2
        in_range = ((non_null >= -8.0) & (non_null <= 2.0)).sum()
    
    confidence = in_range / len(non_null)
    return confidence if confidence >= threshold else 0.0

In [24]:
def detect_cities(series, known_cities=None, threshold=0.6):
    """
    Detect if column contains city names.
    known_cities: set of known city names for matching.
    Returns confidence score (0-1).
    """
    if known_cities is None:
        known_cities = {
            "glasgow", "edinburgh", "aberdeen", "dundee", "inverness",
            "london", "manchester", "birmingham", "cardiff", "belfast"
        }
    
    non_null = series.dropna().astype(str).str.strip().str.lower()
    if len(non_null) == 0:
        return 0.0
    
    matches = non_null.isin(known_cities).sum()
    confidence = matches / len(non_null)
    
    return confidence if confidence >= threshold else 0.0

In [25]:
def detect_regions(series, known_regions=None, threshold=0.6):
    """
    Detect if column contains region names.
    known_regions: set of known region names for matching.
    Returns confidence score (0-1).
    """
    if known_regions is None:
        known_regions = {
            "scotland", "england", "wales", "northern ireland"
        }
    
    non_null = series.dropna().astype(str).str.strip().str.lower()
    if len(non_null) == 0:
        return 0.0
    
    matches = non_null.isin(known_regions).sum()
    confidence = matches / len(non_null)
    
    return confidence if confidence >= threshold else 0.0

In [26]:
def detect_house_type(series, confidence=0.6):
    """
    Detect house type column based on common house type keywords.
    Returns column name if detected, else None.
    """
    house_type_keywords = {
        "high-rise flat", "detached house", "semi-detached", 
        "terraced", "bungalow", "apartment", "cottage", "maisonette",
        "duplex", "studio", "villa", "townhouse"
    }
    
    non_null = series.dropna().astype(str).str.strip().str.lower()
    
    if len(non_null) == 0:
        return 0.0
    
    matches = non_null.isin(house_type_keywords).sum()
    confidence = matches / len(non_null)
    
    return confidence if confidence >= confidence else 0.0

In [27]:
def detect_epc_rating_column(series, threshold=0.7):
    """
    Detect if column contains EPC ratings (A-G).
    Returns confidence score (0-1).
    """
    valid_ratings = {'a', 'b', 'c', 'd', 'e', 'f', 'g'}
    
    non_null = series.dropna().astype(str).str.strip().str.lower()
    if len(non_null) == 0:
        return 0.0
    
    matches = non_null.isin(valid_ratings).sum()
    confidence = matches / len(non_null)
    
    return confidence if confidence >= threshold else 0.0

In [28]:
def auto_detect_column_types(df):
    """
    Automatically detect column types using heuristics.
    Returns dictionary with column names and detected types with confidence.
    """
    results = {}
    
    for col in df.columns:
        series = df[col]
        detections = {}
        
        # Run all detectors
        detections['postcode'] = detect_postcode_column(series)
        detections['uprn'] = detect_uprn_column(series)
        detections['date'], date_fmt = detect_date_column(series)
        detections['address'] = detect_address_column(series)
        detections['numeric_id'], is_seq = detect_numeric_id_column(series)
        detections['categorical'], unique_count = detect_categorical_column(series)
        detections['boolean'] = detect_boolean_column(series)
        detections['year'] = detect_year_column(series)
        detections['latitude'] = detect_coordinate_column(series, 'lat')
        detections['longitude'] = detect_coordinate_column(series, 'lon')
        detections['city'] = detect_cities(series)
        detections['region'] = detect_regions(series)
        detections['house_type'] = detect_house_type(series)
        detections['epc_rating'] = detect_epc_rating_column(series)
        
        if detections['latitude'] > 0.8:
            best_type = 'latitude'
            best_confidence = detections['latitude']
        elif detections['longitude'] > 0.8:
            best_type = 'longitude'
            best_confidence = detections['longitude']
        else:
            best_type = max(detections, key=detections.get)
            best_confidence = detections[best_type]
        
        
        if best_confidence > 0:
            results[col] = {
                'detected_type': best_type,
                'confidence': best_confidence,
                'all_scores': detections
            }
            
            # Add metadata
            if best_type == 'date' and date_fmt:
                results[col]['format'] = date_fmt
            elif best_type == 'numeric_id':
                results[col]['is_sequential'] = is_seq
            elif best_type == 'categorical':
                results[col]['unique_count'] = unique_count
        else:
            results[col] = {
                'detected_type': 'unknown',
                'confidence': 0.0,
                'all_scores': detections
            }
    
    return results

In [29]:
data = df.copy()

In [30]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                1000 non-null   int64
 1   uprn              1000 non-null   object
 2   address           1000 non-null   object
 3   city              914 non-null    object
 4   region            790 non-null    object
 5   postcode          1000 non-null   object
 6   lat               1000 non-null   float64
 7   lon               1000 non-null   float64
 8   buildYear         1000 non-null   int32
 9   type              855 non-null    object
 10  tenure            822 non-null    object
 11  landlord          798 non-null    object
 12  epcRating         871 non-null    object
 13  deprivationindex  1000 non-null   float64
 14  floodscore        1000 non-null   float64
 15  crimeindex        1000 non-null   float64
 16  lastClaimDate     1000 non-null   object
 17  claimFrequency    1000 non-null   float64
 18  expectedseverity  1000 non-null   int32
 19  purepremium       1000 non-null   int32
 20  maintenancescore  1000 non-null   float64
 21  voiddayslastyear  1000 non-null   int32
 22  riskBand          833 non-null    object
dtypes: float64(7), int32(4), int64(1), object(11)
memory usage: 164.2+ KB

In [31]:
data.columns = [f'Column_{i+1}' for i in range(len(data.columns))]
data.head()

,Column_1,Column_2,Column_3,Column_4,Column_5,Column_6,Column_7,Column_8,Column_9,Column_10,...,Column_14,Column_15,Column_16,Column_17,Column_18,Column_19,Column_20,Column_21,Column_22,Column_23
0,1,100084475106,18 Park Road,Manchester,Wales,AB40 2GH,55.21,-3.71,2014,None,...,4.38,0.56,7.33,2022-09-18,1.44,2123,736,4.21,290,Very Low
1,2,100045329879,160 Main Street,Belfast,England,AB57 5AB,55.43,-2.15,2014,None,...,5.71,0.11,4.32,2023-04-23,1.35,5091,523,8.51,99,Very High
2,3,100079434601,52 Church Lane,Dundee,England,G91 5GH,58.36,1.30,2002,None,...,5.31,0.04,7.49,2025-09-05,0.85,3609,1432,2.65,284,Very Low
3,4,100017737414,149 Park Road,Glasgow,Northern Ireland,DD22 6EF,55.43,1.31,1968,Detached House,...,8.83,0.20,5.22,2025-06-09,0.12,1356,345,6.55,319,None
4,5,100097137528,91 High Street,Birmingham,None,EH82 2GH,52.00,-6.30,1999,Terraced,...,7.67,0.95,6.69,2022-07-25,1.57,554,927,6.50,208,Very High

In [32]:
auto_detect_column_types(data)["Column_17"]

{'detected_type': 'date',
 'confidence': 1.0,
 'all_scores': {'postcode': 0.0,
  'uprn': 0.0,
  'date': 1.0,
  'address': 0.0,
  'numeric_id': 0.0,
  'categorical': 0.0,
  'boolean': 0.0,
  'year': 0.0,
  'latitude': 0.0,
  'longitude': 0.0,
  'city': 0.0,
  'region': 0.0,
  'house_type': 0.0,
  'epc_rating': 0.0},
 'format': '%Y-%m-%d'}

python -m uvicorn api:app --reload --port 8000